modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL = "https://github.com/2676959/server_waypoint/issues"

[[mods]]
modId = "server_waypoint"
version = "${version}"
displayName = "${name}"
authors = "2676959"
description = "Share and manage waypoints with chat commands and navigation. Add client screens, in-world markers and Xaero or supported VoxelMap sync with the optional client mod. Supports cross-server waypoints through Velocity."
displayURL = "https://modrinth.com/plugin/server_waypoint"
logoFile = "server_waypoint.png"
logoBlur = false
iconFile = "server_waypoint.png"

[[dependencies.${id}]]
modId="minecraft"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="${minecraft_dependency}"
ordering="NONE"
side="BOTH"

# Xaero's Minimap
[[dependencies.${id}]]
modId="xaerominimap"
type="optional"
versionRange="[25.2.6,)"
ordering="NONE"
side="CLIENT"

# Xaero's World Map
[[dependencies.${id}]]
modId="xaeroworldmap"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="CLIENT"
<% if (voxelmap) { %>
# VoxelMap
[[dependencies.${id}]]
modId="voxelmap"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="CLIENT"
<% } %>
[[mixins]]
config = "server_waypoint-common.mixins.json"
<% if (voxelmap) { %>
[[mixins]]
config = "server_waypoint-voxelmap.mixins.json"
<% } %>
