# Compatible Minecraft Versions
mcVersionForge=[1.21.3, 1.21.4]

# Build Information
mcVersionRange=1.21.3-1.21.4

# Neoforge Properties
neoforge_loader=21.3.96

# Xaero's Minimap
xaeros_minimap_neoforge=neoforge-1.21.3-25.3.5
xaeros_world_map_neoforge=neoforge-1.21.3-1.40.6
xaerolib_neoforge=1.0.45
