# Compatible Minecraft Versions
mcVersionFabric=>=26.3

# Build Information
mcVersionRange=26.3

# Fabric Properties
fabric_loader=0.19.3
fabric_api=0.160.7+26.3
fabric_permissions_api=0.7.0

# Xaero's Mods
xaeros_minimap_fabric=fabric-26.3-26.5.3
xaeros_world_map_fabric=fabric-26.3-1.46.3
xaerolib_fabric=1.7.17

# VoxelMap
voxelmap_fabric=v1UlBIk4
