package _959.server_waypoint.noisespike;

import com.eatthepath.noise.NamedProtocolHandshakeBuilder;
import com.eatthepath.noise.NoiseHandshake;
import com.eatthepath.noise.NoiseTransport;

import javax.crypto.AEADBadTagException;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.IOException;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.Arrays;
import java.util.HashSet;
import java.util.HexFormat;
import java.util.List;
import java.util.Set;

/** Disposable loopback dependency probe, not the feature's transport or credential format. */
public final class NoisePeer {
    public static final String PROTOCOL = "Noise_NKpsk0_25519_AESGCM_SHA256";
    private static final int TIMEOUT_MILLIS = 5_000;
    private static final byte[] PROLOGUE = "server-waypoint-step-2-probe-v1".getBytes(StandardCharsets.US_ASCII);

    private NoisePeer() {
    }

    public static void main(String[] args) throws Exception {
        if (args.length != 4) {
            throw new IllegalArgumentException("Expected role, credential file, port file, scenario");
        }
        boolean server = switch (args[0]) {
            case "server" -> true;
            case "client" -> false;
            default -> throw new IllegalArgumentException("Invalid role");
        };
        String scenario = args[3];
        if (!Set.of("success", "wrong-psk", "wrong-pin", "wrong-prologue", "tamper-request",
                "tamper-response").contains(scenario)) {
            throw new IllegalArgumentException("Invalid scenario");
        }
        int sessions = scenario.equals("success") ? 3 : 1;
        Set<String> handshakeHashes = new HashSet<>();
        if (server) {
            try (ServerSocket listener = new ServerSocket()) {
                listener.bind(new InetSocketAddress(InetAddress.getLoopbackAddress(), 0));
                listener.setSoTimeout(TIMEOUT_MILLIS);
                Path portFile = Path.of(args[2]);
                Path readyFile = portFile.resolveSibling("port.ready");
                Files.writeString(readyFile, Integer.toString(listener.getLocalPort()));
                Files.move(readyFile, portFile, StandardCopyOption.ATOMIC_MOVE);
                for (int session = 0; session < sessions; session++) {
                    try (Socket socket = listener.accept()) {
                        exchange(socket, true, Path.of(args[1]), scenario, session, handshakeHashes);
                    }
                }
            }
        } else {
            int port = Integer.parseInt(Files.readString(Path.of(args[2])));
            for (int session = 0; session < sessions; session++) {
                try (Socket socket = new Socket()) {
                    socket.connect(new InetSocketAddress(InetAddress.getLoopbackAddress(), port), TIMEOUT_MILLIS);
                    exchange(socket, false, Path.of(args[1]), scenario, session, handshakeHashes);
                }
            }
        }
        System.out.println(args[0] + " " + scenario + " PASS sessions=" + sessions);
    }

    private static NoiseHandshake handshake(boolean server, Path credentials, String scenario) throws Exception {
        // These bounded binary fixtures are generated by tests and are never production credentials.
        try (DataInputStream input = new DataInputStream(Files.newInputStream(credentials))) {
            byte[] publicKey = readFrame(input);
            byte[] privateKey = readFrame(input);
            byte[] psk = readFrame(input);
            if (psk.length != 32 || input.read() != -1) {
                throw new IOException("Invalid test fixture");
            }
            var keyFactory = KeyFactory.getInstance("X25519");
            var remotePublicKey = keyFactory.generatePublic(new X509EncodedKeySpec(publicKey));
            var builder = new NamedProtocolHandshakeBuilder(PROTOCOL,
                    server ? NoiseHandshake.Role.RESPONDER : NoiseHandshake.Role.INITIATOR);
            byte[] prologue = PROLOGUE.clone();
            if (!server && scenario.equals("wrong-prologue")) {
                prologue[0] ^= 1;
            }
            builder.setPrologue(prologue).setPreSharedKeys(List.of(psk));
            if (server) {
                builder.setLocalStaticKeyPair(new KeyPair(remotePublicKey,
                        keyFactory.generatePrivate(new PKCS8EncodedKeySpec(privateKey))));
            } else {
                builder.setRemoteStaticPublicKey(remotePublicKey);
            }
            try {
                return builder.build();
            } finally {
                Arrays.fill(privateKey, (byte) 0);
                // Candidate retains the PSK array until handshake processing; do not erase it early.
            }
        }
    }

    private static void exchange(Socket socket, boolean server, Path credentials, String scenario,
                                 int session, Set<String> handshakeHashes) throws Exception {
        socket.setSoTimeout(TIMEOUT_MILLIS);
        DataInputStream input = new DataInputStream(socket.getInputStream());
        DataOutputStream output = new DataOutputStream(socket.getOutputStream());
        NoiseHandshake handshake = handshake(server, credentials, scenario);
        boolean responseTampered = scenario.equals("tamper-response");
        boolean negative = !scenario.equals("success");
        boolean completed = false;
        try {
            if (server) {
                requireEmpty(handshake.readMessage(readFrame(input)));
                byte[] response = handshake.writeMessage(new byte[0]);
                if (responseTampered) {
                    response[response.length - 1] ^= 1;
                }
                writeFrame(output, response);
            } else {
                byte[] request = handshake.writeMessage(new byte[0]);
                if (scenario.equals("tamper-request")) {
                    request[request.length - 1] ^= 1;
                }
                writeFrame(output, request);
                requireEmpty(handshake.readMessage(readFrame(input)));
            }
            if (!handshake.isDone()) {
                throw new IllegalStateException("Handshake did not finish");
            }
            NoiseTransport transport = handshake.toTransport();
            completed = true;
            if (!handshakeHashes.add(HexFormat.of().formatHex(handshake.getHash()))) {
                throw new IllegalStateException("Reconnect reused a handshake hash");
            }
            if (negative) {
                if (server && responseTampered && input.read() == -1) {
                    // Initiator must close without sending any application bytes after the bad response.
                    return;
                }
                throw new IllegalStateException("Negative handshake admitted application traffic");
            }
            // Both directions and multiple counters, including the largest legal Noise plaintext.
            for (int size : new int[]{0, 31, 65_519}) {
                byte[] request = payload(size, session + 1);
                byte[] response = payload(size, session + 17);
                if (server) {
                    requireEqual(request, transport.readMessage(readFrame(input)));
                    writeFrame(output, transport.writeMessage(response));
                } else {
                    byte[] ciphertext = transport.writeMessage(request);
                    if (ciphertext.length != request.length + 16 || Arrays.equals(request, ciphertext)) {
                        throw new IllegalStateException("Transport did not encrypt");
                    }
                    writeFrame(output, ciphertext);
                    requireEqual(response, transport.readMessage(readFrame(input)));
                }
            }
            socket.shutdownOutput();
            if (input.read() != -1) {
                throw new IOException("Expected peer shutdown");
            }
        } catch (AEADBadTagException rejected) {
            if (!negative || completed || server == responseTampered) {
                throw rejected;
            }
            // Only the authenticating side may report a tag failure. Closing the socket is mandatory.
        } catch (EOFException rejected) {
            if (!negative || server || responseTampered || completed) {
                throw rejected;
            }
            // The rejecting responder closes before returning a handshake message.
        }
    }

    private static byte[] payload(int size, int seed) {
        byte[] bytes = new byte[size];
        for (int i = 0; i < bytes.length; i++) {
            bytes[i] = (byte) (i * 31 + seed);
        }
        return bytes;
    }

    private static void requireEmpty(byte[] actual) {
        requireEqual(new byte[0], actual);
    }

    private static void requireEqual(byte[] expected, byte[] actual) {
        if (!Arrays.equals(expected, actual)) {
            throw new IllegalStateException("Payload mismatch");
        }
    }

    public static byte[] readFrame(DataInputStream input) throws IOException {
        int length = input.readInt();
        if (length < 0 || length > 65_535) {
            throw new IOException("Invalid probe frame length");
        }
        byte[] frame = new byte[length];
        input.readFully(frame);
        return frame;
    }

    public static void writeFrame(DataOutputStream output, byte[] bytes) throws IOException {
        if (bytes.length > 65_535) {
            throw new IOException("Probe frame too large");
        }
        output.writeInt(bytes.length);
        output.write(bytes);
        output.flush();
    }
}
