# Compatible Minecraft Versions
mcVersionFabric=>=1.21 <=1.21.1

# Build Information
mcVersionRange=1.21-1.21.1

# Fabric Properties
# check these on https://fabricmc.net/develop
fabric_api=0.102.0+1.21
fabric_permissions_api=0.3.1

# Xaero's Mods
xaeros_minimap_fabric=25.2.6_Fabric_1.21
xaeros_world_map_fabric=1.39.12_Fabric_1.21

# VoxelMap
voxelmap_fabric=QZuVdvFR
