# Compatible Minecraft Versions
mcVersionForge=[1.20.3, 1.20.4]

# Build Information
mcVersionRange=1.20.3-1.20.4

# Neoforge Properties
neoforge_loader=20.4.251

# Xaero's Minimap
xaeros_minimap_neoforge=25.2.10_NeoForge_1.20.4
xaeros_world_map_neoforge=neoforge-1.20.4-1.41.0
xaerolib_neoforge=1.1.15
