# Compatible Minecraft Versions
mcVersionFabric=1.21.11

# Build Information
mcVersionRange=1.21.11

# Fabric Properties
# check these on https://fabricmc.net/develop
fabric_api=0.141.3+1.21.11
fabric_permissions_api=0.6.0

# Xaero's Mods
xaeros_minimap_fabric=fabric-1.21.11-25.3.10
xaeros_world_map_fabric=fabric-1.21.11-1.40.16
xaerolib_fabric=1.1.0

# VoxelMap
voxelmap_fabric=oL15yOzL
