# Compatible Minecraft Versions
mcVersionFabric=>=1.21.6 <=1.21.8

# Build Information
mcVersionRange=1.21.6-1.21.8

# Fabric Properties
# check these on https://fabricmc.net/develop
fabric_api=0.128.2+1.21.6
fabric_permissions_api=0.4.0

# Xaero's Mods
xaeros_minimap_fabric=25.2.7_Fabric_1.21.6
xaeros_world_map_fabric=1.39.10_Fabric_1.21.6

# VoxelMap
voxelmap_fabric=u4XKpU6e
