# Compatible Minecraft Versions
mcVersionForge=[1.21.2, 1.21.4]

# Build Information
mcVersionRange=1.21.2-1.21.4

# Neoforge Properties
neoforge_loader=21.2.1-beta

# Xaero's Minimap
xaeros_minimap_neoforge=25.2.6_NeoForge_1.21.3
xaeros_world_map_neoforge=neoforge-1.21.3-1.40.6
xaerolib_neoforge=1.0.45
xaerolib_neoforge_minecraft=1.21.3
